### ISSUE TITLE
Example Photo

### ISSUE THREAD

**Issue by garrettmaring** [garrettmaring/gridCSS#1]
![screen shot 2015-10-18 at 10 26 48 pm](https://cloud.githubusercontent.com/assets/8270120/10570477/3ee2b1d2-75e9-11e5-9266-454923763105.png)

**Comment by geraldarthurdavis** [comment]
<img width="1394" alt="screen shot 2015-10-20 at 9 00 56 pm" src="https://cloud.githubusercontent.com/assets/8270120/10627398/b2362d64-776d-11e5-9543-5c8125dd8784.png">
